// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Ph4smzz6iRVuA0LCvUBN6BK29955ZU0',
    appId: '1:420424546471:web:bdc3e1ebf491998f440382',
    messagingSenderId: '420424546471',
    projectId: 'riverpod-auth-d3dc3',
    authDomain: 'riverpod-auth-d3dc3.firebaseapp.com',
    storageBucket: 'riverpod-auth-d3dc3.firebasestorage.app',
    measurementId: 'G-G0D8VNTVSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBig8ZG8M6-2NHqOL2eFOk7-LjCNCBtDxs',
    appId: '1:420424546471:android:297698f0f60e054d440382',
    messagingSenderId: '420424546471',
    projectId: 'riverpod-auth-d3dc3',
    storageBucket: 'riverpod-auth-d3dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacmPBqRVIlBRmg2mP4ocFNSoKYO0XPsU',
    appId: '1:420424546471:ios:13952dcea7fb5f6c440382',
    messagingSenderId: '420424546471',
    projectId: 'riverpod-auth-d3dc3',
    storageBucket: 'riverpod-auth-d3dc3.firebasestorage.app',
    iosBundleId: 'com.example.riverpodCodegen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBacmPBqRVIlBRmg2mP4ocFNSoKYO0XPsU',
    appId: '1:420424546471:ios:13952dcea7fb5f6c440382',
    messagingSenderId: '420424546471',
    projectId: 'riverpod-auth-d3dc3',
    storageBucket: 'riverpod-auth-d3dc3.firebasestorage.app',
    iosBundleId: 'com.example.riverpodCodegen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Ph4smzz6iRVuA0LCvUBN6BK29955ZU0',
    appId: '1:420424546471:web:d533d7f6f67c1a55440382',
    messagingSenderId: '420424546471',
    projectId: 'riverpod-auth-d3dc3',
    authDomain: 'riverpod-auth-d3dc3.firebaseapp.com',
    storageBucket: 'riverpod-auth-d3dc3.firebasestorage.app',
    measurementId: 'G-DMWQYQ7R42',
  );
}
